modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory

authors="Shadows_of_Fire" #optional

license="MIT License"

[[mods]] #mandatory

modId="apotheosis" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Apotheosis" #mandatory

description='''
All things that should have been.
'''

[[dependencies.apotheosis]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="placebo"
    mandatory=true
    versionRange="[4.3.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="quark"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER" #We need to load before quark, or bad things may happen.
    side="BOTH"

[[dependencies.apotheosis]]
    modId="jei"
    mandatory=false
    versionRange="[7.6.0,)"
    ordering="NONE"
    side="BOTH"